wx:
  mp:
    configs:
      - appId: wx40d294a89bcd9fcb
        secret: e48b8b33730cb8bf7ed2aa26e671549b
        token: zhongchi
        aesKey: HbQ8Z0VJjGXgc5AmyuBMpqmDDj2YJJgNEPVFrDbjoZ2        tmpDirFile: D://AAA
        
   
    server-url: http://zhongchiedu.com
    #server-url: http://m7xm9x.natappfree.cc

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

#激活mongodb配置
spring:  profiles:    active:    - mongodb

qrcode:
  height: 300
  width: 300
  #weburl: http://m7xm9x.natappfree.cc/WXWebApp/
  weburl: http://zhongchiedu.com/WXWebApp/
  format: png
  qrcodepath: upload/qrcode/
upload:
  savedir: D:/
#图片列表配置
  qrCode: upload/qrcode/
#预入库
templateId: C13mVUYAhCV40w12DFrEnvFmuRRErQliLUMbRle4eic 
templateId1: t65Pa8jI77ZTyyTX1LnPNgAYKo1sk8idfR72lbe0I10
templateId2: usdpKAlc3Npb89SnYyQTOw4jVwyCCYFRSgYW1yR68Ek
#出库成功通知
templateId3: vr3-sgtGL2WrhwIU5MImE1vZulEdz2hmTuiBLeupY4Q



